---
- hosts: taiga
  user: taiga
  
  tasks:

  - name: Create a new database with name "taiga" and specific encoding and locale
    postgresql_db:
      name: taiga
      encoding: UTF-8
      lc_collate: en_US.utf8
      lc_ctype: en_US.utf8
      template: template0


  